[package]
name = "doumi-gui"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "doumi-gui"
path = "src/main.rs"

[dependencies]
doumi-core = { path = "../doumi-core" }
anyhow = { workspace = true }
serde_json = { workspace = true }
dirs = { workspace = true }
uuid = { workspace = true }
gtk4 = { version = "0.9", features = ["v4_12"] }
libadwaita = { version = "0.7", features = ["v1_6"] }
